import { expect, test } from '@playwright/test'
test('imports a GIFT deck and starts study', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('基本問題')
  await page.getByLabel('GIFTテキスト').fill('::首都::日本の首都は? {=東京#正解 ~大阪#違います}')
  await page.getByRole('button', { name: '解析する' }).click()
  await expect(page.getByText('1 問を読み込みます。')).toBeVisible()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByText('東京').click()
  await page.getByRole('button', { name: '回答する' }).click()
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
  await page.getByRole('button', { name: '正解' }).click()
  await expect(page.getByRole('heading', { name: '今日の学習は完了です' })).toBeVisible()
  await expect(page.getByRole('link', { name: '問題集へ戻る' })).toHaveAttribute(
    'href',
    /\/decks\//,
  )
  await page.reload()
  await page.goto('/decks')
  await page.getByText('基本問題').click()
  await expect(page.getByText('1回答')).toBeVisible()
  await page.goto('/history')
  await expect(page.getByText('100%').first()).toBeVisible()
  await page.goto('/settings')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'JSONを保存' }).click()
  const download = await downloadPromise
  const backupPath = test.info().outputPath('backup.json')
  await download.saveAs(backupPath)
  page.once('dialog', (dialog) => dialog.accept())
  await Promise.all([
    page.waitForURL((url) => url.pathname === '/'),
    page.getByRole('button', { name: 'すべて削除' }).click(),
  ])
  await page.goto('/settings')
  await Promise.all([
    page.waitForEvent('framenavigated'),
    page.locator('input[type=file][accept*="json"]').setInputFiles(backupPath),
  ])
  await expect(page.getByRole('heading', { name: '設定' })).toBeVisible()
  await page.waitForLoadState('networkidle')
  await page.getByRole('link', { name: '問題集' }).click()
  await expect(page.getByText('基本問題')).toBeVisible()
})

test('can switch a deck to flashcard mode and self-rate the revealed answer', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('単語帳')
  await page.getByLabel('GIFTテキスト').fill('日本の首都は? {=東京 ~大阪}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('radio', { name: /単語帳/ }).check()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await expect(page.getByText('東京', { exact: true })).toBeHidden()
  await expect(page.getByText('大阪', { exact: true })).toBeHidden()
  await page.getByRole('button', { name: '答えを見る' }).click()
  await expect(page.getByRole('heading', { name: '正答' })).toBeVisible()
  await expect(page.getByText('東京', { exact: true })).toBeVisible()
  await expect(page.getByText('大阪', { exact: true })).toBeHidden()
  await page.getByRole('button', { name: 'わかった' }).click()
  await expect(page.getByRole('heading', { name: '今日の学習は完了です' })).toBeVisible()
})

test('accepts a decimal numerical answer with Enter', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('数値問題')
  await page.getByLabel('GIFTテキスト').fill('円周率 {#=3.14:0.01}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByLabel('数値で解答').fill('3.14')
  await expect(page.getByRole('button', { name: '回答する' })).toBeEnabled()
  await page.getByLabel('数値で解答').press('Enter')
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
})

test('accepts a decimal numerical answer with the answer button', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('数値問題ボタン')
  await page.getByLabel('GIFTテキスト').fill('円周率 {#=3.14:0.01}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByLabel('数値で解答').fill('3.14')
  await page.getByRole('button', { name: '回答する' }).click()
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
})

test('shows the correct short answer after an incorrect answer', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('短答問題')
  await page.getByLabel('GIFTテキスト').fill('日本の首都は? {=東京 =東京都}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByLabel('解答').fill('大阪')
  await page.getByLabel('解答').press('Enter')
  await expect(page.getByText(/不正解（0点）/)).toBeVisible()
  await expect(page.getByText('正しい答え: 東京 / 東京都')).toBeVisible()
})

test('does not submit a short answer while Japanese IME composition is active', async ({
  page,
}) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('短答IME問題')
  await page.getByLabel('GIFTテキスト').fill('日本の首都は? {=東京 =東京都}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  const answer = page.getByLabel('解答')
  await answer.fill('東京')
  await answer.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(page.getByText(/正解（100点）/)).toBeHidden()
  await answer.press('Enter')
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
})

test('can study a deck in cram mode when no questions are due', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('詰め込み問題集')
  await page.getByLabel('GIFTテキスト').fill('Q {TRUE}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByText('正しい', { exact: true }).click()
  await page.getByRole('button', { name: '回答する' }).click()
  await page.getByRole('button', { name: '正解' }).click()
  await expect(page.getByRole('heading', { name: '今日の学習は完了です' })).toBeVisible()

  await page.goto('/decks')
  await page.getByText('詰め込み問題集').click()
  await expect(page.getByRole('link', { name: '全問を詰め込み学習' })).toBeVisible()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await expect(page.getByText('詰め込み学習', { exact: true })).toBeVisible()
  await expect(page.getByText('Q', { exact: true })).toBeVisible()
})

test('gives partial credit and allows Again or Hard after a partial answer', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('複数選択')
  await page.getByLabel('GIFTテキスト').fill('Q {~%50%A ~%50%B ~%-50%C ~%-50%D}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByText('A', { exact: true }).click()
  await page.getByText('C', { exact: true }).click()
  await page.getByRole('button', { name: '回答する' }).click()
  await expect(page.getByText(/不正解（50点）/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'もう一度' })).toBeEnabled()
  await expect(page.getByRole('button', { name: '難しかった' })).toBeEnabled()
  await expect(page.getByRole('button', { name: '正解' })).toBeDisabled()
  await expect(page.getByRole('button', { name: '簡単' })).toBeDisabled()
  await page.getByRole('button', { name: '難しかった' }).click()
  await expect(page.getByRole('heading', { name: '今日の学習は完了です' })).toBeVisible()
  await page.goto('/history')
  await expect(page.getByText('hard', { exact: true })).toBeVisible()
})

test('can defer answer feedback until the learner reveals it', async ({ page }) => {
  await page.goto('/settings')
  await page.getByLabel('回答直後に正誤と解説を表示する').uncheck()
  await expect(page.getByText('保存しました')).toBeVisible()
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('遅延フィードバック')
  await page.getByLabel('GIFTテキスト').fill('Q {=yes ~no}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByText('yes').click()
  await page.getByRole('button', { name: '回答する' }).click()
  await expect(page.getByText(/正解（100点）/)).toBeHidden()
  await page.getByRole('button', { name: '結果と解説を表示' }).click()
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
})

test('translates import, deck detail, and study pages into English', async ({ page }) => {
  await page.goto('/settings')
  await page.getByLabel('言語').selectOption('en')
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()

  await page.goto('/import')
  await expect(page.getByRole('heading', { name: 'Import GIFT' })).toBeVisible()
  await page.getByLabel('Deck name').fill('English deck')
  await page.getByLabel('GIFT text').fill('Capital of Japan? {=Tokyo ~Osaka}')
  await page.getByRole('button', { name: 'Analyze' }).click()
  await expect(page.getByText('Import 1 question.')).toBeVisible()
  await page.getByRole('button', { name: 'Save as deck' }).click()

  await expect(page.getByRole('heading', { name: 'Study mode' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Questions' })).toBeVisible()
  await page.getByRole('radio', { name: /Flashcards/ }).check()
  await page.getByRole('link', { name: 'Study this deck' }).click()
  await expect(page.getByRole('button', { name: 'Reveal answer' })).toBeVisible()
  await page.getByRole('button', { name: 'Reveal answer' }).click()
  await expect(page.getByRole('heading', { name: 'Correct answer' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Understood' })).toBeVisible()
})
