import { expect, test } from '@playwright/test'
test('imports a GIFT deck and starts study', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('基本問題')
  await page.getByLabel('GIFTテキスト').fill('::首都::日本の首都は? {=東京#正解 ~大阪#違います}')
  await page.getByRole('button', { name: '解析する' }).click()
  await expect(page.getByText('1 問を読み込みます。')).toBeVisible()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByText('東京').click()
  await page.getByRole('button', { name: '回答する' }).click()
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
  await page.getByRole('button', { name: '正解' }).click()
  await expect(page.getByRole('heading', { name: '1問正解' })).toBeVisible()
  await expect(page.getByRole('link', { name: '問題集へ戻る' })).toHaveAttribute(
    'href',
    /\/decks\//,
  )
  await page.reload()
  await page.goto('/decks')
  await page.getByText('基本問題').click()
  await expect(page.getByText('1回答')).toBeVisible()
  await expect(page.getByLabel('Rating: もう一度 0、難しかった 0、正解 1、簡単 0')).toBeVisible()
  await expect(page.locator('.rating-pill.good.active')).toHaveText('正解 1')
  const studyLink = page.getByRole('link', { name: 'この問題集を学習' })
  const studyLinkBox = await studyLink.boundingBox()
  await page.getByRole('button', { name: '「首都」をプレビュー' }).click()
  await expect(page.getByRole('heading', { name: '首都' })).toBeVisible()
  await expect(page.getByText('日本の首都は?', { exact: true })).toBeVisible()
  await expect(page.getByText('東京', { exact: true })).toBeVisible()
  if (!studyLinkBox) throw new Error('Study link is not visible')
  await page.mouse.click(
    studyLinkBox.x + studyLinkBox.width / 2,
    studyLinkBox.y + studyLinkBox.height / 2,
  )
  await expect(page.getByRole('heading', { name: '首都' })).toBeHidden()
  await expect(page).toHaveURL(/\/decks\//)
  await page.getByRole('button', { name: '「首都」をプレビュー' }).click()
  await page.getByRole('button', { name: '閉じる' }).click()
  await page.getByRole('button', { name: '履歴をリセット' }).click()
  const resetDialog = page.getByRole('dialog', { name: '学習履歴のリセット' })
  await expect(resetDialog).toBeVisible()
  await resetDialog.getByRole('button', { name: 'キャンセル' }).click()
  await page.getByRole('button', { name: '問題集を削除' }).click()
  const deleteDialog = page.getByRole('dialog', { name: '問題集の削除' })
  await expect(deleteDialog).toBeVisible()
  await deleteDialog.getByRole('button', { name: 'キャンセル' }).click()
  await page.goto('/history')
  await expect(page.getByText('100%').first()).toBeVisible()
  await page.goto('/settings')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'JSONを保存' }).click()
  const download = await downloadPromise
  const backupPath = test.info().outputPath('backup.json')
  await download.saveAs(backupPath)
  page.once('dialog', (dialog) => dialog.accept())
  await Promise.all([
    page.waitForURL((url) => url.pathname === '/'),
    page.getByRole('button', { name: 'すべて削除' }).click(),
  ])
  await page.goto('/settings')
  await Promise.all([
    page.waitForEvent('framenavigated'),
    page.locator('input[type=file][accept*="json"]').setInputFiles(backupPath),
  ])
  await expect(page.getByRole('heading', { name: '設定' })).toBeVisible()
  await page.waitForLoadState('networkidle')
  await page.getByRole('link', { name: '問題集' }).click()
  await expect(page.getByText('基本問題')).toBeVisible()
})

test('rebuilds the study queue when an empty session has become stale', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => {
    sessionStorage.setItem(
      'fukushu-study-session-v1',
      JSON.stringify({ deckId: null, cram: false, questionIds: [] }),
    )
  })
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('空セッション後の問題集')
  await page.getByLabel('GIFTテキスト').fill('新しく追加した問題 {TRUE}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await expect(page).toHaveURL(/\/decks\//)
  await page.goto('/')
  await page.getByRole('link', { name: '学習を始める' }).click()
  await expect(page.getByText('新しく追加した問題', { exact: true })).toBeVisible()
})

test('can switch a deck to flashcard mode and self-rate the revealed answer', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('単語帳')
  await page.getByLabel('GIFTテキスト').fill('日本の首都は? {=東京 ~大阪}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('radio', { name: /単語帳/ }).check()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await expect(page.getByText('東京', { exact: true })).toBeHidden()
  await expect(page.getByText('大阪', { exact: true })).toBeHidden()
  await page.getByRole('button', { name: '答えを見る' }).click()
  await expect(page.getByRole('heading', { name: '正答' })).toBeVisible()
  await expect(page.getByText('東京', { exact: true })).toBeVisible()
  await expect(page.getByText('大阪', { exact: true })).toBeHidden()
  await page.getByRole('button', { name: 'わかった' }).click()
  await expect(page.getByRole('heading', { name: '1問正解' })).toBeVisible()
})

test('accepts a decimal numerical answer with Enter', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('数値問題')
  await page.getByLabel('GIFTテキスト').fill('円周率 {#=3.14:0.01}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByLabel('数値で解答').fill('3.14')
  await expect(page.getByRole('button', { name: '回答する' })).toBeEnabled()
  await page.getByLabel('数値で解答').press('Enter')
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
})

test('accepts a decimal numerical answer with the answer button', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('数値問題ボタン')
  await page.getByLabel('GIFTテキスト').fill('円周率 {#=3.14:0.01}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByLabel('数値で解答').fill('3.14')
  await page.getByRole('button', { name: '回答する' }).click()
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
})

test('shows the correct short answer after an incorrect answer', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('短答問題')
  await page.getByLabel('GIFTテキスト').fill('日本の首都は? {=東京 =東京都}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByLabel('解答').fill('大阪')
  await page.getByLabel('解答').press('Enter')
  await expect(page.getByText(/不正解（0点）/)).toBeVisible()
  await expect(page.getByText('正しい答え: 東京 / 東京都')).toBeVisible()
})

test('does not submit a short answer while Japanese IME composition is active', async ({
  page,
}) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('短答IME問題')
  await page.getByLabel('GIFTテキスト').fill('日本の首都は? {=東京 =東京都}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  const answer = page.getByLabel('解答')
  await answer.fill('東京')
  await answer.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(page.getByText(/正解（100点）/)).toBeHidden()
  await answer.press('Enter')
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
})

test('can study a deck in cram mode when no questions are due', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('詰め込み問題集')
  await page.getByLabel('GIFTテキスト').fill('Q {TRUE}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByText('正しい', { exact: true }).click()
  await page.getByRole('button', { name: '回答する' }).click()
  await page.getByRole('button', { name: '正解' }).click()
  await expect(page.getByRole('heading', { name: '1問正解' })).toBeVisible()

  await page.goto('/decks')
  await page.getByText('詰め込み問題集').click()
  await expect(page.getByRole('link', { name: '全問を詰め込み学習' })).toBeVisible()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await expect(page.getByText('詰め込み学習', { exact: true })).toBeVisible()
  await expect(page.getByText('Q', { exact: true })).toBeVisible()
})

test('gives partial credit and allows Again or Hard after a partial answer', async ({ page }) => {
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('複数選択')
  await page.getByLabel('GIFTテキスト').fill('Q {~%50%A ~%50%B ~%-50%C ~%-50%D}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByText('A', { exact: true }).click()
  await page.getByText('C', { exact: true }).click()
  await page.getByRole('button', { name: '回答する' }).click()
  await expect(page.getByText(/不正解（50点）/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'もう一度' })).toBeEnabled()
  await expect(page.getByRole('button', { name: '難しかった' })).toBeEnabled()
  await expect(page.getByRole('button', { name: '正解' })).toBeDisabled()
  await expect(page.getByRole('button', { name: '簡単' })).toBeDisabled()
  await page.getByRole('button', { name: '難しかった' }).click()
  await expect(page.getByRole('heading', { name: '0問正解' })).toBeVisible()
  await page.goto('/history')
  await expect(page.getByText('hard', { exact: true })).toBeVisible()
})

test('can defer answer feedback until the learner reveals it', async ({ page }) => {
  await page.goto('/settings')
  await page.getByLabel('回答直後に正誤と解説を表示する').uncheck()
  await expect(page.getByText('保存しました')).toBeVisible()
  await page.goto('/import')
  await page.getByLabel('問題集名').fill('遅延フィードバック')
  await page.getByLabel('GIFTテキスト').fill('Q {=yes ~no}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()
  await page.getByText('yes').click()
  await page.getByRole('button', { name: '回答する' }).click()
  await expect(page.getByText(/正解（100点）/)).toBeHidden()
  await page.getByRole('button', { name: '結果と解説を表示' }).click()
  await expect(page.getByText(/正解（100点）/)).toBeVisible()
})

test('shows configurable progress reports and a detailed final result', async ({ page }) => {
  await page.goto('/settings')
  await page.getByLabel('途中結果を表示する回答数').fill('2')
  await expect(page.getByText('保存しました')).toBeVisible()

  await page.goto('/import')
  await page.getByLabel('問題集名').fill('途中結果')
  await page
    .getByLabel('GIFTテキスト')
    .fill('::Q1::1問目 {TRUE}\n\n::Q2::2問目 {TRUE}\n\n::Q3::3問目 {TRUE}')
  await page.getByRole('button', { name: '解析する' }).click()
  await page.getByRole('button', { name: '問題集として保存' }).click()
  await page.getByRole('link', { name: 'この問題集を学習' }).click()

  await page.getByText('正しい', { exact: true }).click()
  await page.getByRole('button', { name: '回答する' }).click()
  await page.getByRole('button', { name: '正解' }).click()

  await page.getByRole('button', { name: '中断する' }).click()
  await expect(page.getByText('中断時点の結果', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '1問正解' })).toBeVisible()
  await expect(page.locator('.result-table-wrap tbody tr')).toHaveCount(1)
  await expect(page.getByRole('link', { name: '問題集へ戻る' })).toBeVisible()
  await page.reload()
  await expect(page.getByText('中断時点の結果', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '学習を続ける' }).click()

  await page.getByText('誤り', { exact: true }).click()
  await page.getByRole('button', { name: '回答する' }).click()
  await page.getByRole('button', { name: '難しかった' }).click()

  await expect(page.getByText('途中結果', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '1問正解' })).toBeVisible()
  await expect(page.getByText('誤答 1問・回答 2問・正答率 50%')).toBeVisible()
  const resultQuestions = page.locator('.result-table-wrap tbody tr')
  await expect(resultQuestions).toHaveCount(2)
  await expect(resultQuestions.first().locator('.result-badge-incorrect')).toBeVisible()
  await expect(page.getByText('難しかった', { exact: true })).toBeVisible()
  await resultQuestions
    .first()
    .getByRole('button', { name: /プレビュー/ })
    .click()
  const previewDialog = page.getByRole('dialog')
  await expect(previewDialog).toBeVisible()
  await expect(previewDialog).toHaveCSS('text-align', 'left')
  await page.getByRole('button', { name: '閉じる' }).click()
  await expect(page.getByLabel('共有用の結果テキスト')).toHaveValue(
    /結果: 正答1問\/誤答1問\/回答2問 \(正答率50%\)/,
  )
  await expect(page.getByRole('button', { name: 'コピー' })).toBeVisible()

  await page.reload()
  await expect(page.getByText('途中結果', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '学習を続ける' }).click()
  await page.getByText('正しい', { exact: true }).click()
  await page.getByRole('button', { name: '回答する' }).click()
  await page.getByRole('button', { name: '簡単' }).click()

  await expect(page.getByText('学習結果', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '2問正解' })).toBeVisible()
  await expect(page.getByText('誤答 1問・回答 3問・正答率 67%')).toBeVisible()
  await expect(page.locator('.result-table-wrap tbody tr')).toHaveCount(3)
})

test('translates import, deck detail, and study pages into English', async ({ page }) => {
  await page.goto('/settings')
  await page.getByLabel('言語').selectOption('en')
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()

  await page.goto('/import')
  await expect(page.getByRole('heading', { name: 'Import GIFT' })).toBeVisible()
  await page.getByLabel('Deck name').fill('English deck')
  await page.getByLabel('GIFT text').fill('Capital of Japan? {=Tokyo ~Osaka}')
  await page.getByRole('button', { name: 'Analyze' }).click()
  await expect(page.getByText('Import 1 question.')).toBeVisible()
  await page.getByRole('button', { name: 'Save as deck' }).click()

  await expect(page.getByRole('heading', { name: 'Study mode' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Questions' })).toBeVisible()
  await page.getByRole('radio', { name: /Flashcards/ }).check()
  await page.getByRole('link', { name: 'Study this deck' }).click()
  await expect(page.getByRole('button', { name: 'Reveal answer' })).toBeVisible()
  await page.getByRole('button', { name: 'Reveal answer' }).click()
  await expect(page.getByRole('heading', { name: 'Correct answer' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Understood' })).toBeVisible()
})
